import React from "react"
import Head from "next/head"
import Navbar from "./General/Navbar"
import Container from "./General/Container"

const Layout = ({ children }: any) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      {children}
    </>
  )
}

export default Layout
