import React from "react"
import Head from "next/head"
import Navbar from "./General/Navbar"
import { useRouter } from "next/router"

const Layout = ({ children }: any) => {
  const { pathname } = useRouter()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {pathname !== "/404" && <Navbar />}
      {children}
    </>
  )
}

export default Layout
